version: 2
jobs:
  test:
    working_directory: ~/rn-hero-design
    docker:
      - image: ehdevops/node:0.1.3
    environment:
      - CI: true
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

