defaults: &defaults
  working_directory: ~/rn-hero-design
  docker:
    - image: ehdevops/node:0.1.3
  environment:
    - CI: true

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install --ignore-engines
      - run: yarn test
  build_ts:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install --ignore-engines
      - run: yarn ts:build
  publish_lib:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install --ignore-engines
      - run: yarn lib:build
      # - run:
      #     name: Authenticate with registry
      #     command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: cd lib && npm publish
  deploy_doc:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install --ignore-engines
      - run: yarn lib:build
      - run: yarn doc:deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          context: org-global
      - build_ts:
          context: org-global
      - publish_lib:
          context: org-global
          filters:
            branches:
              only:
                - release
          requires:
            - test
            - hold_publish
      # - deploy_doc:
      #     context: org-global
      #     filters:
      #       branches:
      #         only:
      #           - release
      #     requires:
      #       - test
      #       - hold_publish
      - hold_publish:
          type: approval
          filters:
            branches:
              only:
                - release

