defaults: &defaults
  working_directory: ~/rn-hero-design
  docker:
    - image: ehdevops/node:0.1.3
  environment:
    - CI: true

version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  publish_lib:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: yarn lib:publish
  deploy_doc:
    <<: *defaults
    steps:
      - checkout
      - run: yarn install
      - run: yarn doc:deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test:
          context: org-global
      - publish_lib:
          context: org-global
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - hold_publish
      - deploy_doc:
          context: org-global
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - hold_publish
      - hold_publish:
          type: approval
          filters:
            branches:
              only: master

